apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rba-pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: master
  - name: runbook-dir
    type: string
    description: sub directory where runbook source is located
    default: ""
  - name: runbook-name
    type: string
    description: name of the runbook to be installed
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: runbook_dir
      value: $(params.runbook-dir)
    - name: runbook_name
      value: $(params.runbook-name)
    runAfter:
    - fetch-repository