apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-runbook
spec:
  workspaces:
  - name: source
  - name: config
  - name: secret
  params:
    - name: runbook-dir
      description: The directory in workspace that contains the runbook manifest
      type: string
      default: ""
    - name: runbook-name
      description: The name of the runbook to deploy
      type: string
      default: "runbook"
  steps:
    - name: apply
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/$(inputs.params.runbook-dir)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          source /workspace/config/rba-env.properties
          source /workspace/secret/rba-credentials.properties
          echo Applying Runbook $(inputs.params.runbook_name) manifests in $(inputs.params.runbook-dir) directory
          echo API Endpoint: $API_ENDPOINT
          echo API Key: $API_KEY
          ls /workspace/source
          echo -----------------------------------