apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: runbook-deployment-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: runbook-trigger-binding
  template:
    ref: runbook-trigger-template
